parameters:
    max_row: 20
    
services:
    ass_rssfeed.saveXML:
        class: Assetment\RssfeedBundle\Services\SaveXML
    ass_rssfeed.fetch:
        class: Assetment\RssfeedBundle\Services\FetchRss
#        arguments: ["@service_container"]
#    assetment_rssfeed.example:
#        class: Assetment\RssfeedBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
